export const API_ENDPOINTS = {
  login: "/auth/login",
  register: "/auth/register",
  users: "/users",
  products:"/products",
  cart:"/cart",
  wishlist:"/wishlist",
  orders:"/orders",
  collectionbrands:'/brands',
  home: "/home",
  deals:"/deals",
  categoryBanners:"category-banners",
  collections: "/collections",
  getActiveOfferApi: "/offers/active",
  GET_ALL: "/brands",
  GET_SINGLE: (id) => `/brands/${id}`,
  categoryGet:`/categories`,
  newArrivals: `/newarrivals`,
  bestSellers:`/bestSellers`,
};